name: Deploy Discord Bot to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for connecting to the droplet
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MANTID_DROPLET_KEY }} 

      # Step 3: Deploy to the droplet
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@157.230.181.201 << 'EOF'
          cd Mantid
          
          # Pull the latest code from the GitHub repository
          git pull origin main
          source venv/bin/activate
          
          # Install Python dependencies
          pip install -U pip
          pip install -r requirements.txt
          
          # Restart the Discord bot (or start it if not running)
          pkill -f run.py || true
          nohup python3 run.py &
          EOF
